# Generated by Django 4.2.1 on 2023-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=True)),
                ("userid", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("createdDateTime", models.CharField(max_length=50)),
                ("introduction", models.CharField(max_length=999)),
                ("courseTags", models.CharField(max_length=300)),
                ("startLocationName", models.CharField(max_length=100)),
                ("locations", models.CharField(max_length=9999)),
            ],
        ),
    ]
