// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0iUIRrgVuGP_QQxywe7a1S4LxsoPoABc',
    appId: '1:264255583598:web:48312c4b00b449edbfbd7f',
    messagingSenderId: '264255583598',
    projectId: 'wearebility-303e9',
    authDomain: 'wearebility-303e9.firebaseapp.com',
    storageBucket: 'wearebility-303e9.appspot.com',
    measurementId: 'G-CR918VFGYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrbRi7gQ_pl92RtdAD9EO-F6Q6bXI5tBg',
    appId: '1:264255583598:android:c31c328b3d07f79abfbd7f',
    messagingSenderId: '264255583598',
    projectId: 'wearebility-303e9',
    storageBucket: 'wearebility-303e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbAtmGxo_rh6gBrwHpdnghFJ68_jFfIcs',
    appId: '1:264255583598:ios:95d98edab66e62fdbfbd7f',
    messagingSenderId: '264255583598',
    projectId: 'wearebility-303e9',
    storageBucket: 'wearebility-303e9.appspot.com',
    androidClientId: '264255583598-1l5492e5nuj82lkklkq43qd1a1phsno9.apps.googleusercontent.com',
    iosClientId: '264255583598-0ms7g4lp5fakn4ougodsq712nrbf5cm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.naemansan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbAtmGxo_rh6gBrwHpdnghFJ68_jFfIcs',
    appId: '1:264255583598:ios:95d98edab66e62fdbfbd7f',
    messagingSenderId: '264255583598',
    projectId: 'wearebility-303e9',
    storageBucket: 'wearebility-303e9.appspot.com',
    androidClientId: '264255583598-1l5492e5nuj82lkklkq43qd1a1phsno9.apps.googleusercontent.com',
    iosClientId: '264255583598-0ms7g4lp5fakn4ougodsq712nrbf5cm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.naemansan',
  );
}
